name: Code Checks
on: pull_request
jobs:
  library:
    uses: reformcollective/library/.github/workflows/code-checks.yml@main
    secrets:
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
